#!/usr/bin/env bash
# Displays information about subdomains

# Arguments
DOMAIN=$1
SUBDOMAIN=$2

# Function to audit a given subdomain
# Usage: check_domain subdomain domain
check_domain() {
    local sub=$1
    local dom=$2
    # Identifying record type and destination using dig and awk
    # shellcheck disable=SC2086
    dig $sub.$dom | awk -v sub_name="$sub" '
        !/^;/ && /\s+IN\s+(A|CNAME)\s+/ {
            print "The subdomain " sub_name " is a " $4 " record and points to " $5
        }
    '
}

# Main logic
if [ -n "$DOMAIN" ] && [ -n "$SUBDOMAIN" ]; then
    # When both domain and subdomain are provided
    check_domain "$SUBDOMAIN" "$DOMAIN"
elif [ -n "$DOMAIN" ]; then
    # When only domain is provided, check default subdomains in order
    check_domain "www" "$DOMAIN"
    check_domain "lb-01" "$DOMAIN"
    check_domain "web-01" "$DOMAIN"
    check_domain "web-02" "$DOMAIN"
fi
