#!/usr/bin/env bash
# Configures a new Ubuntu machine to the requirements
# of task 0 of the Load balancer project.

# shellcheck disable=SC2154

# Set hostname based on server IP
if [[ $(hostname -I) == *"44.205.246.25"* ]]; then
    sudo hostnamectl --set-hostname 67000-web-01
elif [[ $(hostname -I) == *"54.173.9.253"* ]]; then
    sudo hostnamectl --set-hostname 67000-web-02
fi

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Add custom header X-Served-By with hostname to default site config
sudo sed -i "s/server_name _;/server_name _;\\n\\tadd_header X-Served-By \$hostname;/" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
