#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine
# to distribute traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get -y install haproxy

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy frontend and backend
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend ines_frontend
    bind *:80
    default_backend ines_backend

backend ines_backend
    balance roundrobin
    server 67000-web-01 44.205.246.25:80 check
    server 67000-web-02 54.173.9.253:80 check
EOF

sudo service haproxy restart