#!/usr/bin/env bash
# Install and configure HAProxy load balancer

apt-get update
apt-get -y install haproxy

echo "ENABLED=1" | tee /etc/default/haproxy

cat <<EOF >> /etc/haproxy/haproxy.cfg

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.204.136.7:80 check
    server web-02 44.201.166.17:80 check
EOF

service haproxy restart
