#!/usr/bin/env bash
# Configures web-01
sudo hostnamectl --set-hostname 67000-web-01
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Creates a simple HTML page in the default web root
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Add custom header X-Served-By with hostname
sudo sed -i "s/server_name _;/server_name _;\\n\\tadd_header X-Served-By \$hostname;/" /etc/nginx/sites-available/default

# Restarts the nginx service
sudo service nginx start