#!/usr/bin/env bash
# Configures Nginx with custom 404 and redirect

apt-get update -y
apt-get install -y nginx

# Allow HTTP
ufw allow 'Nginx HTTP'

# Create index page
echo "Holberton School" | tee /var/www/html/index.html > /dev/null

# Create custom 404 page (NO newline issues)
printf "Ceci n'est pas une page" | tee /var/www/html/404.html > /dev/null

# Overwrite nginx default configuration (ACTIVE FILE)
cat <<EOF > /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart nginx
service nginx restart